#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DisplayPort-1 -d I II III IV
bspc monitor HDMI-A-0 -d V VI VII VIII

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc rule -a firefox desktop='^1'
bspc rule -a pulsemixer state=floating
bspc rule -a htop state=floating
bspc rule -a xfreerdp state=floating

# Autostart
polybar -q zeus-left &
polybar -q zeus-right &
