#! /bin/sh
bspc monitor DisplayPort-0 -d 1 2 3 4 
bspc monitor HDMI-A-0 -d 5 6 7 8

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action2 resize_corner

bspc config external_rules_command ".local/bin/bspwm-rules"

bspc config automatic_scheme longest_side

# Dracula-Theme
bspc config normal_border_color "#44475a"
bspc config active_border_color "#6272a4"
bspc config focused_border_color "#bd93f9"
bspc config presel_feedback_color "#6272a4"

# Apply tall-layout as default
bsp-layout set tall 1
bsp-layout set tall 2
bsp-layout set tall 3
bsp-layout set tall 4
bsp-layout set tall 5
bsp-layout set tall 6
bsp-layout set tall 7
bsp-layout set tall 8

# Autostart
pgrep -x sxhkd > /dev/null || sxhkd &
restart-polybar

