#! /bin/sh
bspc monitor DisplayPort-1 -d 1 2 3 4 
bspc monitor HDMI-A-0 -d 5 6 7 8

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action2 resize_corner

bspc config external_rules_command ".local/bin/bspwm-rules"

# Autostart
pgrep -x sxhkd > /dev/null || sxhkd &

killall -q polybar
polybar -q zeus-left &
polybar -q zeus-right &

